name       : pv
version    : 1.7.24
release    : 5
homepage   : http://www.ivarch.com/programs/pv.shtml
source     :
    - https://www.ivarch.com/programs/sources/pv-1.7.24.tar.gz : 3bf43c5809c8d50066eaeaea5a115f6503c57a38c151975b710aa2bee857b65e
license    : Artistic License 2.0
summary    : A terminal-based tool for monitoring the progress of data through a pipeline.
component  : system.utils
description: |
    Pipe Viewer - is a terminal-based tool for monitoring the progress of data through a pipeline.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
