name       : pv
version    : 1.6.0
release    : 1
homepage   : http://www.ivarch.com/programs/pv.shtml
source     :
    - http://www.ivarch.com/programs/sources/pv-1.6.0.tar.gz : 9dd45391806b0ed215abee4c5ac1597d018c386fe9c1f5afd2f6bc3b07fd82c3
license    : Artistic License 2.0
summary    : A terminal-based tool for monitoring the progress of data through a pipeline.
description: |
    Pipe Viewer - is a terminal-based tool for monitoring the progress of data through a pipeline.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
