name       : pv
version    : 1.6.6
release    : 2
homepage   : http://www.ivarch.com/programs/pv.shtml
source     :
    - http://www.ivarch.com/programs/sources/pv-1.6.6.tar.gz : 94defb4183ae07c44219ba298d43c4991d6e203c29f74393d72ecad3b090508a
license    : Artistic License 2.0
summary    : A terminal-based tool for monitoring the progress of data through a pipeline.
component  : system.utils
description: |
    Pipe Viewer - is a terminal-based tool for monitoring the progress of data through a pipeline.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
